# Generated by Django 3.0.5 on 2023-03-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20230304_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hospital.Room', verbose_name='number'),
        ),
    ]
