# Generated by Django 3.0.5 on 2023-03-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20230304_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dischargeDate',
        ),
    ]
