# Generated by Django 3.0.5 on 2023-03-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_remove_patient_dischargedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admitDate',
        ),
    ]
