# Generated by Django 3.0.5 on 2023-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_remove_patient_admitdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='room',
        ),
        migrations.AddField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dischargeDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
