# Generated by Django 3.0.5 on 2023-03-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_auto_20230304_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
