# Generated by Django 4.1.7 on 2023-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0031_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default=None, max_length=40),
        ),
    ]
