# Generated by Django 4.1.7 on 2023-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0032_remove_patient_user_patient_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(default=None, max_length=250),
        ),
    ]
