# Generated by Django 4.1.7 on 2023-03-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0033_patient_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
    ]
