# Generated by Django 4.1.7 on 2023-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0035_remove_room_available_room_cost_room_max_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
